#ifndef _WEBPAGES_H_
#define _WEBPAGES_H_

const char* htmlForm = "<html>\n"
                      "<head>\n"
                      "<title>ICBaliza configuration</title>\n"
                      "<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap\">\n"
                      "<style>\n"
                      "  body { display: flex; align-items: center; justify-content: center; height: 100vh; background-color: #f4f4f4; font-family: 'Roboto', sans-serif; }\n"
                      "  form { background-color: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); max-width: 400px; width: 100%; text-align: center; }\n"
                      "  label { display: block; margin-bottom: 8px; }\n"
                      "  input { width: 100%; padding: 8px; margin-bottom: 16px; box-sizing: border-box; border: 1px solid #ccc; border-radius: 4px; }\n"
                      "  input[type=\"submit\"] { background-color: #4caf50; color: #fff; cursor: pointer; }\n"
                      "  h1 { color: #333; font-size: 28px; margin-bottom: 20px; }\n"
                      "</style>\n"
                      "</head>\n"
                      "<body>\n"
                      "<form action=\"submit\" method=\"post\">\n"

                      "  <h1>ICBaliza</h1>\n"

                      "  <label for=\"ssid\">SSID:</label>\n"
                      "  <input type=\"text\" id=\"ssid\" name=\"ssid\"><br><br>\n"

                      "  <label for=\"password\">Password:</label>\n"
                      "  <input type=\"password\" id=\"password\" name=\"password\"><br><br>\n"

                      "  <label for=\"retry\">Retry Number:</label>\n"
                      "  <input type=\"number\" id=\"retry\" name=\"retry\"><br><br>\n"

                      "  <label for=\"repository\">Repository name:</label>\n"
                      "  <input type=\"text\" id=\"repository\" name=\"repository\"><br><br>\n"

                      "  <label for=\"owner\">Repository Owner:</label>\n"
                      "  <input type=\"text\" id=\"owner\" name=\"owner\"><br><br>\n"

                      "  <label for=\"authorization\">Authorization:</label>\n"
                      "  <input type=\"text\" id=\"authorization\" name=\"authorization\"><br><br>\n"

                      "  <input type=\"submit\" value=\"Submit\">\n"
                      "</form>\n"
                      "</body>\n"
                      "</html>\n";


const char* htmlMessage = "<!DOCTYPE html>\n"
                          "<html lang=\"en\">\n"
                          "<head>\n"
                          "    <meta charset=\"UTF-8\">\n"
                          "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                          "    <title>ICBaliza Configuration successful</title>\n"
                          "    <style>\n"
                          "        body {\n"
                          "            display: flex;\n"
                          "            align-items: center;\n"
                          "            justify-content: center;\n"
                          "            height: 100vh;\n"
                          "            background-color: #f4f4f4;\n"
                          "            font-family: Arial, sans-serif;\n"
                          "        }\n"
                          "\n"
                          "        table {\n"
                          "            border-collapse: collapse;\n"
                          "            width: 50%;\n"
                          "            text-align: center;\n"
                          "        }\n"
                          "\n"
                          "        th, td {\n"
                          "            padding: 20px;\n"
                          "            border: 1px solid #ddd;\n"
                          "        }\n"
                          "\n"
                          "        h1 {\n"
                          "            color: #333;\n"
                          "            font-size: 24px;\n"
                          "            margin-bottom: 20px;\n"
                          "        }\n"
                          "    </style>\n"
                          "</head>\n"
                          "<body>\n"
                          "    <table>\n"
                          "        <tr>\n"
                          "            <th colspan=\"2\">\n"
                          "                <h1>ICBaliza Configuration</h1>\n"
                          "            </th>\n"
                          "        </tr>\n"
                          "        <tr>\n"
                          "            <td colspan=\"2\">\n"
                          "                <p>ICBaliza was configured successfully with the received parameters. If the blue light persists after 45 seconds, please check the parameters sent and try again.</p>\n"
                          "            </td>\n"
                          "        </tr>\n"
                          "    </table>\n"
                          "</body>\n"
                          "</html>\n";                      

#endif // _WEBPAGES_H_